local M = {}

function M.set(col16, col30)
    return {
        DevIconAac                  = { bg = "none", },
        DevIconAi                   = { bg = "none", },
        DevIconAlmalinux            = { bg = "none", },
        DevIconAlpine               = { fg = col30.blue, bg = "none", },
        DevIconAOSC                 = { bg = "none", },
        DevIconApp                  = { bg = "none", },
        DevIconApple                = { bg = "none", },
        DevIconAppleScript          = { bg = "none", },
        DevIconArch                 = { fg = col30.blue, bg = "none", },
        DevIconArtix                = { bg = "none", },
        DevIconAvif                 = { bg = "none", },
        DevIconAwk                  = { bg = "none", },
        DevIconAzureCli             = { bg = "none", },
        DevIconBabelrc              = { bg = "none", },
        DevIconBash                 = { bg = "none", },
        DevIconBashProfile          = { bg = "none", },
        DevIconBashrc               = { bg = "none", },
        DevIconBat                  = { bg = "none", },
        DevIconBazel                = { bg = "none", },
        DevIconBazelBuild           = { bg = "none", },
        DevIconBazelWorkspace       = { bg = "none", },
        DevIconBibTeX               = { bg = "none", },
        DevIconBinaryGLTF           = { bg = "none", },
        DevIconBmp                  = { bg = "none", },
        DevIconBrewfile             = { bg = "none", },
        DevIconBudgie               = { bg = "none", },
        DevIconBzl                  = { bg = "none", },
        DevIconCentos               = { bg = "none", },
        DevIconc                    = { fg = col30.blue, bg = "none", },
        DevIconCjs                  = { bg = "none", },
        DevIconClojure              = { bg = "none", },
        DevIconClojureC             = { bg = "none", },
        DevIconClojureDart          = { bg = "none", },
        DevIconClojureJS            = { bg = "none", },
        DevIconCMake                = { bg = "none", },
        DevIconCMakeLists           = { bg = "none", },
        DevIconCobol                = { bg = "none", },
        DevIconCoffee               = { bg = "none", },
        DevIconConf                 = { bg = "none", },
        DevIconConfigRu             = { bg = "none", },
        DevIconConfiguration        = { bg = "none", },
        DevIconCp                   = { bg = "none", },
        DevIconCPlusPlus            = { bg = "none", },
        DevIconCpp                  = { bg = "none", },
        DevIconCrystal              = { bg = "none", },
        DevIconCs                   = { bg = "none", },
        DevIconCSharpProject        = { bg = "none", },
        DevIconCsh                  = { bg = "none", },
        DevIconCson                 = { bg = "none", },
        DevIconcss                  = { fg = col30.blue, bg = "none", },
        DevIconCsv                  = { bg = "none", },
        DevIconCts                  = { bg = "none", },
        DevIconCxx                  = { bg = "none", },
        DevIconDart                 = { fg = col30.cyan, bg = "none", },
        DevIconDb                   = { bg = "none", },
        DevIconD                    = { bg = "none", },
        DevIcondeb                  = { fg = col30.cyan, bg = "none", },
        DevIconDebian               = { bg = "none", },
        DevIconDeepin               = { bg = "none", },
        DevIconDefault              = { bg = "none", },
        DevIconDesktopEntry         = { bg = "none", },
        DevIconDevuan               = { bg = "none", },
        DevIconDiff                 = { bg = "none", },
        DevIconDoc                  = { bg = "none", },
        DevIconDockerfile           = { fg = col30.cyan, bg = "none", },
        DevIconDocx                 = { bg = "none", },
        DevIconDrools               = { bg = "none", },
        DevIconDropbox              = { bg = "none", },
        DevIconDsStore              = { bg = "none", },
        DevIconDump                 = { bg = "none", },
        DevIconEditorConfig         = { bg = "none", },
        DevIconEdn                  = { bg = "none", },
        DevIconEex                  = { bg = "none", },
        DevIconEjs                  = { bg = "none", },
        DevIconElementary           = { bg = "none", },
        DevIconElf                  = { bg = "none", },
        DevIconElm                  = { bg = "none", },
        DevIconEmbeddedOpenTypeFont = { bg = "none", },
        DevIconEndeavour            = { bg = "none", },
        DevIconEnv                  = { bg = "none", },
        DevIconEpp                  = { bg = "none", },
        DevIconErb                  = { bg = "none", },
        DevIconErl                  = { bg = "none", },
        DevIconEslintIgnore         = { bg = "none", },
        DevIconEslintrc             = { bg = "none", },
        DevIconEx                   = { bg = "none", },
        DevIconExe                  = { bg = "none", },
        DevIconExs                  = { bg = "none", },
        DevIconFavicon              = { bg = "none", },
        DevIconFedora               = { bg = "none", },
        DevIconFennel               = { bg = "none", },
        DevIconFish                 = { bg = "none", },
        DevIconFlac                 = { bg = "none", },
        DevIconFortran              = { bg = "none", },
        DevIconFreeBSD              = { bg = "none", },
        DevIconFs                   = { bg = "none", },
        DevIconFsharp               = { bg = "none", },
        DevIconFsi                  = { bg = "none", },
        DevIconFsscript             = { bg = "none", },
        DevIconFsx                  = { bg = "none", },
        DevIconGDScript             = { bg = "none", },
        DevIconGemfile              = { bg = "none", },
        DevIconGemspec              = { bg = "none", },
        DevIconGentoo               = { bg = "none", },
        DevIconGif                  = { bg = "none", },
        DevIconGitAttributes        = { bg = "none", },
        DevIconGitCommit            = { bg = "none", },
        DevIconGitConfig            = { bg = "none", },
        DevIconGitIgnore            = { bg = "none", },
        DevIconGitlabCI             = { bg = "none", },
        DevIconGitLogo              = { bg = "none", },
        DevIconGitModules           = { bg = "none", },
        DevIconGo                   = { bg = "none", },
        DevIconGodotProject         = { bg = "none", },
        DevIconGraphQL              = { bg = "none", },
        DevIconGruntfile            = { bg = "none", },
        DevIconGuix                 = { bg = "none", },
        DevIconGulpfile             = { bg = "none", },
        DevIconGvimrc               = { bg = "none", },
        DevIconHaml                 = { bg = "none", },
        DevIconH                    = { bg = "none", },
        DevIconHbs                  = { bg = "none", },
        DevIconHeex                 = { bg = "none", },
        DevIconHh                   = { bg = "none", },
        DevIconHpp                  = { bg = "none", },
        DevIconHrl                  = { bg = "none", },
        DevIconHs                   = { bg = "none", },
        DevIconHtm                  = { bg = "none", },
        DevIconhtml                 = { fg = col30.baby_pink, bg = "none", },
        DevIconHuff                 = { bg = "none", },
        DevIconHurl                 = { bg = "none", },
        DevIconHxx                  = { bg = "none", },
        DevIconIco                  = { bg = "none", },
        DevIconIllumos              = { bg = "none", },
        DevIconImportConfiguration  = { bg = "none", },
        DevIconIni                  = { bg = "none", },
        DevIconJava                 = { fg = col30.orange, bg = "none", },
        DevIconJavaScriptReactSpec  = { bg = "none", },
        DevIconJavaScriptReactTest  = { bg = "none", },
        DevIconJl                   = { bg = "none", },
        DevIconjpeg                 = { fg = col30.dark_purple, bg = "none", },
        DevIconJpegXl               = { bg = "none", },
        DevIconjpg                  = { fg = col30.dark_purple, bg = "none", },
        DevIconjs                   = { fg = col30.sun, bg = "none", },
        DevIconJson5                = { bg = "none", },
        DevIconJson                 = { bg = "none", },
        DevIconJsonc                = { bg = "none", },
        DevIconJSX                  = { fg = col30.blue, bg = "none", },
        DevIconKali                 = { bg = "none", },
        DevIconKotlin               = { bg = "none", },
        DevIconKotlinScript         = { bg = "none", },
        DevIconKsh                  = { bg = "none", },
        DevIconkt                   = { fg = col30.orange, bg = "none", },
        DevIconLeex                 = { bg = "none", },
        DevIconLess                 = { bg = "none", },
        DevIconLhs                  = { bg = "none", },
        DevIconLicense              = { bg = "none", },
        DevIconLinux                = { bg = "none", },
        DevIconLiquid               = { bg = "none", },
        DevIconlock                 = { fg = col30.red, bg = "none", },
        DevIconLog                  = { bg = "none", },
        DevIconlua                  = { fg = col30.blue, bg = "none", },
        DevIconLuau                 = { bg = "none", },
        DevIconLuaurc               = { bg = "none", },
        DevIconM4A                  = { bg = "none", },
        DevIconM4V                  = { bg = "none", },
        DevIconMageia               = { bg = "none", },
        DevIconMakefile             = { bg = "none", },
        DevIconManjaro              = { bg = "none", },
        DevIconMarkdown             = { bg = "none", },
        DevIconMaterial             = { bg = "none", },
        DevIconMd                   = { fg = col30.blue, bg = "none", },
        DevIconMdx                  = { bg = "none", },
        DevIconMint                 = { bg = "none", },
        DevIconMixLock              = { bg = "none", },
        DevIconMjs                  = { bg = "none", },
        DevIconMkv                  = { bg = "none", },
        DevIconMl                   = { bg = "none", },
        DevIconMli                  = { bg = "none", },
        DevIconMotoko               = { bg = "none", },
        DevIconMOV                  = { bg = "none", },
        DevIconmp3                  = { fg = col30.white, bg = "none", },
        DevIconmp4                  = { fg = col30.white, bg = "none", },
        DevIconMts                  = { bg = "none", },
        DevIconMustache             = { bg = "none", },
        DevIconNim                  = { bg = "none", },
        DevIconNix                  = { bg = "none", },
        DevIconNixOS                = { bg = "none", },
        DevIconNodeModules          = { bg = "none", },
        DevIconNPMIgnore            = { bg = "none", },
        DevIconNPMrc                = { bg = "none", },
        DevIconNswag                = { bg = "none", },
        DevIconOgg                  = { bg = "none", },
        DevIconOpenBSD              = { bg = "none", },
        DevIconopenSUSE             = { bg = "none", },
        DevIconOpenTypeFont         = { bg = "none", },
        DevIconOPUS                 = { bg = "none", },
        DevIconOrgMode              = { bg = "none", },
        DevIconout                  = { fg = col30.white, bg = "none", },
        DevIconPackageJson          = { bg = "none", },
        DevIconPackageLockJson      = { bg = "none", },
        DevIconPackedResource       = { bg = "none", },
        DevIconParrot               = { bg = "none", },
        DevIconPdf                  = { bg = "none", },
        DevIconPhp                  = { bg = "none", },
        DevIconPl                   = { bg = "none", },
        DevIconPm                   = { bg = "none", },
        DevIconpng                  = { fg = col30.dark_purple, bg = "none", },
        DevIconPop_OS               = { bg = "none", },
        DevIconPp                   = { bg = "none", },
        DevIconPpt                  = { bg = "none", },
        DevIconPrisma               = { bg = "none", },
        DevIconProcfile             = { bg = "none", },
        DevIconProlog               = { bg = "none", },
        DevIconPsb                  = { bg = "none", },
        DevIconPsd                  = { bg = "none", },
        DevIconPsManifestfile       = { bg = "none", },
        DevIconPsScriptfile         = { bg = "none", },
        DevIconPsScriptModulefile   = { bg = "none", },
        DevIconPxd                  = { bg = "none", },
        DevIconPxi                  = { bg = "none", },
        DevIconPy                   = { bg = "none", },
        DevIconPyc                  = { bg = "none", },
        DevIconPyd                  = { bg = "none", },
        DevIconpy                   = { fg = col30.cyan, bg = "none", },
        DevIconPyi                  = { bg = "none", },
        DevIconPyo                  = { bg = "none", },
        DevIconPyx                  = { bg = "none", },
        DevIconQuery                = { bg = "none", },
        DevIconRake                 = { bg = "none", },
        DevIconRakefile             = { bg = "none", },
        DevIconRaspberryPiOS        = { bg = "none", },
        DevIconRazorPage            = { bg = "none", },
        DevIconrb                   = { fg = col30.pink, bg = "none", },
        DevIconR                    = { bg = "none", },
        DevIconRedhat               = { bg = "none", },
        DevIconReScript             = { bg = "none", },
        DevIconReScriptInterface    = { bg = "none", },
        DevIconRlib                 = { bg = "none", },
        DevIconRmd                  = { bg = "none", },
        DevIconRockyLinux           = { bg = "none", },
        DevIconrpm                  = { fg = col30.orange, bg = "none", },
        DevIconRproj                = { bg = "none", },
        DevIconRs                   = { bg = "none", },
        DevIconRss                  = { bg = "none", },
        DevIconSabayon              = { bg = "none", },
        DevIconSass                 = { bg = "none", },
        DevIconsbt                  = { bg = "none", },
        DevIconScala                = { bg = "none", },
        DevIconScheme               = { bg = "none", },
        DevIconScss                 = { bg = "none", },
        DevIconSettingsJson         = { bg = "none", },
        DevIconSh                   = { bg = "none", },
        DevIconSig                  = { bg = "none", },
        DevIconSlackware            = { bg = "none", },
        DevIconSlim                 = { bg = "none", },
        DevIconSln                  = { bg = "none", },
        DevIconSml                  = { bg = "none", },
        DevIconSolidity             = { bg = "none", },
        DevIconSolus                = { bg = "none", },
        DevIconSpecJs               = { bg = "none", },
        DevIconSpecTs               = { bg = "none", },
        DevIconSql                  = { bg = "none", },
        DevIconStyl                 = { bg = "none", },
        DevIconSuo                  = { bg = "none", },
        DevIconSvelteConfig         = { bg = "none", },
        DevIconSvelte               = { fg = col30.red, bg = "none", },
        DevIconSvg                  = { bg = "none", },
        DevIconSwift                = { bg = "none", },
        DevIconSystemVerilog        = { bg = "none", },
        DevIconTailwindConfig       = { bg = "none", },
        DevIconTcl                  = { bg = "none", },
        DevIconTempl                = { bg = "none", },
        DevIconTerminal             = { bg = "none", },
        DevIconTerraform            = { bg = "none", },
        DevIconTestJs               = { bg = "none", },
        DevIconTestTs               = { bg = "none", },
        DevIconTex                  = { bg = "none", },
        DevIconTextResource         = { bg = "none", },
        DevIconTextScene            = { bg = "none", },
        DevIconTFVars               = { bg = "none", },
        DevIcontoml                 = { fg = col30.blue, bg = "none", },
        DevIconTor                  = { bg = "none", },
        DevIconTrueTypeFont         = { bg = "none", },
        DevIconTSConfig             = { bg = "none", },
        DevIconts                   = { fg = col30.teal, bg = "none", },
        DevIconTSX                  = { fg = col30.blue, bg = "none", },
        DevIconttf                  = { fg = col30.white, bg = "none", },
        DevIconTwig                 = { bg = "none", },
        DevIconTxt                  = { bg = "none", },
        DevIconTypeScriptReactSpec  = { bg = "none", },
        DevIconTypeScriptReactTest  = { bg = "none", },
        DevIconUbuntu               = { bg = "none", },
        DevIconVagrantfile          = { bg = "none", },
        DevIconVala                 = { bg = "none", },
        DevIconVerilog              = { bg = "none", },
        DevIconVHDL                 = { bg = "none", },
        DevIconVim                  = { bg = "none", },
        DevIconVimrc                = { bg = "none", },
        DevIconVlang                = { bg = "none", },
        DevIconVoid                 = { bg = "none", },
        DevIconvue                  = { fg = col30.vibrant_green, bg = "none", },
        DevIconWasm                 = { bg = "none", },
        DevIconWav                  = { bg = "none", },
        DevIconWebmanifest          = { bg = "none", },
        DevIconWebm                 = { bg = "none", },
        DevIconWebOpenFontFormat    = { bg = "none", },
        DevIconWebpack              = { bg = "none", },
        DevIconWebp                 = { bg = "none", },
        DevIconWindows              = { bg = "none", },
        DevIconwoff2                = { fg = col30.white, bg = "none", },
        DevIconwoff                 = { fg = col30.white, bg = "none", },
        DevIconXaml                 = { bg = "none", },
        DevIconXcPlayground         = { bg = "none", },
        DevIconXls                  = { bg = "none", },
        DevIconXlsx                 = { bg = "none", },
        DevIconXml                  = { bg = "none", },
        DevIconXul                  = { bg = "none", },
        DevIconxz                   = { fg = col30.sun, bg = "none", },
        DevIconYaml                 = { bg = "none", },
        DevIconYml                  = { bg = "none", },
        DevIconZig                  = { fg = col30.orange, bg = "none", },
        DevIconzip                  = { fg = col30.sun, bg = "none", },
        DevIconZorin                = { bg = "none", },
        DevIconZsh                  = { bg = "none", },
        DevIconZshenv               = { bg = "none", },
        DevIconZshprofile           = { bg = "none", },
        DevIconZshrc                = { bg = "none", },
    }
end

return M
