local M = {}

function M.set(col16, col30)
    return {
        ["@annotation"]             = { fg = col16.color0F, ctermfg = 13 },
        ["@attribute"]              = { fg = col16.color0A, ctermfg = 3 },
        ["@character"]              = { fg = col16.color08, ctermfg = 9 },
        ["@constructor"]            = { fg = col16.color0C, ctermfg = 6 },
        ["@constant"]               = { fg = col16.color08, ctermfg = 1 },
        ["@constant.builtin"]       = { fg = col16.color09, ctermfg = 4 },
        ["@constant.macro"]         = { fg = col16.color08, ctermfg = 1 },
        ["@error"]                  = { fg = col16.color08, ctermfg = 9 },
        ["@exception"]              = { fg = col16.color08, ctermfg = 9 },
        ["@float"]                  = { fg = col16.color09, ctermfg = 12 },
        ["@keyword"]                = { fg = col16.color0E, ctermfg = 5 },
        ["@keyword.function"]       = { fg = col16.color0E, ctermfg = 5 },
        ["@keyword.return"]         = { fg = col16.color0E, ctermfg = 5 },
        ["@function"]               = { fg = col16.color0D, ctermfg = 12 },
        ["@function.builtin"]       = { fg = col16.color0D, ctermfg = 12 },
        ["@function.macro"]         = { fg = col16.color08, ctermfg = 1 },
        ["@function.call"]          = { fg = col16.color0D, ctermfg = 4 },
        ["@operator"]               = { fg = col16.color05, ctermfg = 7 },
        ["@keyword.operator"]       = { fg = col16.color0E, ctermfg = 5 },
        ["@method"]                 = { fg = col16.color0D, ctermfg = 4 },
        ["@method.call"]            = { fg = col16.color0D, ctermfg = 4 },
        ["@namespace"]              = { fg = col16.color08, ctermfg = 1 },
        ["@none"]                   = { fg = col16.color05, ctermfg = 7 },
        ["@parameter"]              = { fg = col16.color08, ctermfg = 9 },
        ["@reference"]              = { fg = col16.color05, ctermfg = 7 },
        ["@punctuation.bracket"]    = { fg = col16.color0F, ctermfg = 9 },
        ["@punctuation.delimiter"]  = { fg = col16.color0F, ctermfg = 13 },
        ["@punctuation.special"]    = { fg = col16.color08, ctermfg = 9 },
        ["@string"]                 = { fg = col16.color0B, ctermfg = 2 },
        ["@string.regex"]           = { fg = col16.color0C, ctermfg = 6 },
        ["@string.escape"]          = { fg = col16.color0C, ctermfg = 14 },
        ["@string.special"]         = { fg = col16.color0C, ctermfg = 14 },
        ["@symbol"]                 = { fg = col16.color0B, ctermfg = 2 },
        ["@tag"]                    = { fg = col16.color0A, ctermfg = 3 },
        ["@tag.attribute"]          = { fg = col16.color08, ctermfg = 1 },
        ["@tag.delimiter"]          = { fg = col16.color0F, ctermfg = 5 },
        ["@text"]                   = { fg = col16.color05, ctermfg = 7 },
        ["@text.strong"]            = { bold = true },
        ["@text.emphasis"]          = { fg = col16.color09, ctermfg = 4 },
        ["@text.strike"]            = { fg = col16.color0F, ctermfg = 5, strikethrough = true },
        ["@text.literal"]           = { fg = col16.color09, ctermfg = 4 },
        ["@text.uri"]               = { fg = col16.color09, ctermfg = 4, underline = true },
        ["@type.builtin"]           = { fg = col16.color0A, ctermfg = 3 },
        ["@variable"]               = { fg = col16.color05, ctermfg = 7 },
        ["@variable.builtin"]       = { fg = col16.color09, ctermfg = 12 },
        ["@definition"]             = { sp = col16.color04, underline = true },
        ["@scope"]                  = { bold = true },
        ["@field"]                  = { fg = col16.color08, ctermfg = 1 },
        ["@field.key"]              = { fg = col16.color08, ctermfg = 9 },
        ["@property"]               = { fg = col16.color08, ctermfg = 1 },
        ["@include"]                = { link = "Include" },
        ["@conditional"]            = { fg = col16.color0E, ctermfg = 5 },
        ["@conditional.ternary"]    = { fg = col16.color0E, ctermfg = 5 },
        ["@comment"]                = { fg = col30.grey_fg, ctermfg = 8 },
    }
end

return M
